# -*- coding: utf-8 -*-
"""autoencode8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yRo_H-T4eErosJiNIsujg2G1rQZs8-4e
"""

from math import sqrt
from numpy import concatenate
import tensorflow as tf
import math
import os
import numpy as np

from tensorflow import keras
#from tensorflow.keras import backend as K
from keras import backend as K

import random
#from keras.utils import np_utils

from sklearn.utils import shuffle

X = np.array([[1,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,1],[0,0,0,0,0,0,1,0], [0,0,0,0,0,1,0,0], [0,0,0,0,1,0,0,0],
             [0,0,0,1,0,0,0,0],[0,0,1,0,0,0,0,0],[0,1,0,0,0,0,0,0]])
y = np.array([[1,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,1],[0,0,0,0,0,0,1,0], [0,0,0,0,0,1,0,0], [0,0,0,0,1,0,0,0],
              [0,0,0,1,0,0,0,0],[0,0,1,0,0,0,0,0],[0,1,0,0,0,0,0,0]])

COST_FUNCTION = "mean_squared_error"
    #design Network                                                                                            
model = keras.Sequential()
model.add(keras.layers.Dense(3, input_dim=8, activation='tanh'))
# Output layer                                                                                  
model.add(keras.layers.Dense(8, activation='sigmoid'))
opt = keras.optimizers.Adam(learning_rate=0.08)
model.compile(loss=COST_FUNCTION, optimizer = opt) # ,metrics=['mae'])
print(model.summary())

#print(X.shape)
#print(y.shape)


history = model.fit(X, y, validation_data=(X,y),epochs=800, batch_size=1,
                    verbose=2, shuffle=False)
model.save('autoenc'+'.h5')
predictions = model.predict(X)
predictions=np.round(predictions)
print("Predictions are\n",predictions)
print("Model Weights")
print (model.get_weights())

# This works in jupyter notebook only
get_1st_layer_output = K.function([model.layers[0].input], [model.layers[0].output])

layer_output = get_1st_layer_output(X)[0]
print("Hidden output: ", layer_output)
new_input=layer_output

# Build model to predict from this compressed input (of 3 values) with a single or more layers
# neural network
classifier_model = keras.Sequential()
classifier_model.add(keras.layers.Dense(10, input_dim=3, activation='relu'))
classifier_model.add(keras.layers.Dense(8, activation='softmax'))

# Compile the classifier model
classifier_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the classifier using the hidden layer output
history = classifier_model.fit(layer_output, y, epochs=100, batch_size=1, verbose=0)

# Use the classifier to make predictions
predictions = classifier_model.predict(layer_output)

# Round the predictions to the nearest integer (0 or 1)
rounded_predictions = np.round(predictions)

# Print the raw predictions and rounded predictions
print("Raw predictions:")
print(predictions)
print("Rounded predictions:")
print(rounded_predictions)