/*  http://www.java-examples.com/java-string-split-example
Java String split example.
This Java String split example describes how Java String is split into multiple
Java String objects.
*/
/*
   OUTPUT of the below given Java String split Example would be :
   one two three
   
   one
   two
   three
   
   one
   two.three
*/

public class JavaStringSplitExample{

  public static void main(String args[]){
  /*
  Java String class defines following methods to split Java String object.
  String[] split( String regularExpression )
  Splits the string according to given regular expression.
  String[] split( String reularExpression, int limit )
  Splits the string according to given regular expression. The number of resultant
  substrings by splitting the string is controlled by limit argument.
  */

  /* String to split. */
  String str = "one-two-three";
  String[] temp;  // string array to hold the individual strings (the substrings) once the str is split by the delimiter - 

  /* delimiter */
  String delimiter = "-";
  /* string str will be split by the argument delimiter provided */
  temp = str.split(delimiter);
  /* print the substring/string values */
  for(int i = 0; i < temp.length ; i++)
    System.out.print(temp[i] + " ");
  
  System.out.println();
  
  /*
  IMPORTANT : Some special characters need to be escaped while providing them as
  delimiters like "." and "|".
  */

  System.out.println("");
  str = "one.two.three";
  delimiter = "\\.";
  temp = str.split(delimiter);
  for(int i = 0; i < temp.length ; i++)
    System.out.println(temp[i]);
  
  System.out.println();
  
  /*
  Using second argument in the String.split() method, we can control the maximum
  number of substrings generated by splitting a string.
  */

  System.out.println("");
  temp = str.split(delimiter,2); // limits to having only 2 substrings/strings
  for(int i = 0; i < temp.length ; i++)
    System.out.println(temp[i]);

  }// end main

}// end JavaStringSplitExample